config/routes.rb
Rails.application.routes.draw do
  resources :profiles

  # resources :watchlists

  root 'application#welcome'
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  # devise_for :users
  resources :furnitures#, except: :create
  resources :profiles

  get '/my_watch_list', to: 'watchlists#show'
  get '/my_watch_list/edit', to: 'watchlists#edit'
  post '/furnitures/:id', to: 'furnitures#add_to_watch_list'
  post '/my_watch_list/:furniture_id', to: 'watchlists#unwatch'
  # get '/video/:token', to: 'furnitures#create'
  get '/team', to: 'application#team'
  get '/search', to: 'furnitures#search'
  # resources :users



  # get '/welcome', to: 'application#welcome'
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @profiles = Profile.all
    respond_with(@profiles)
  end

  def show
    @user = @profile.user
    tmp = Geokit::Geocoders::GoogleGeocoder.geocode(@user.address)
    @currentLocation = [tmp.lat, tmp.lng]
    respond_with(@profile)
  end

  def new
    @profile = Profile.new
    respond_with(@profile)
  end

  def edit
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.save
    respond_with(@profile)
  end

  def update
    @profile.update(profile_params)
    respond_with(@profile)
  end

  def destroy
    @profile.destroy
    respond_with(@profile)
  end

  private
    def set_profile
      @profile = Profile.find(params[:id])
      # @profile = Profile.find(params[:id])
    end

    def profile_params
      params.require(:profile).permit(:user_id)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.haml
= form_for @profile do |f|
  - if @profile.errors.any?
    #error_explanation
      %h2= "#{pluralize(@profile.errors.count, "error")} prohibited this profile from being saved:"
      %ul
        - @profile.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user
    = f.text_field :user
  .actions
    = f.submit 'Save'

app/views/profiles/edit.html.haml
%h1 Editing profile

= render 'form'

= link_to 'Show', @profile
\|
= link_to 'Back', profiles_path

app/views/profiles/index.html.haml
%h1 Listing profiles

%table
  %thead
    %tr
      %th User
      %th
      %th
      %th
      
  %tbody
    - @profiles.each do |profile|
      %tr
        %td= profile.user
        %td= link_to 'Show', profile
        %td= link_to 'Edit', edit_profile_path(profile)
        %td= link_to 'Destroy', profile, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Profile', new_profile_path

app/views/profiles/new.html.haml
%h1 New profile

= render 'form'

= link_to 'Back', profiles_path

app/views/profiles/show.html.haml
%section.content-wrapper
  .container
    .row
      .col-md-12
        .content-box
          %h3
            = @user.name
    %p
      %strong
        Email:
        = @user.email
    %p
      %strong
        Phone Number:
        = @user.phone
    %p
      %strong
        Address:
        = @user.address
    %p
      %strong
        Introduction:
        = @user.introduction
    .row
      .col-md-12
        .content-box
          %h3 WHAT HE/SHE SELLS
          .row
            .col-md-12
              .slide-about-people
                - @user.furnitures.each do |furniture|
                  %a{:href => "/furnitures/#{furniture.id}"}
                    .people-block
                      %figure
                        - if furniture.picture1 != nil && furniture.picture1.to_s.strip != ""
                          = image_tag furniture.picture1, size: '300x250'
                        - else
                          = image_tag 'default.jpg', size: "300x250"
                      .people-desc
                        -#%a{:href => "#{profile_path(furniture.user.profile)}", :float => "right"}
                        = furniture.user.name
                        %span.people-name
                          %a{:href => "/furnitures/#{furniture.id}"}
                            = furniture.title
                        %p.line-break
                          - s = furniture.description.to_s.strip
                          - if s.length > 50
                            - s = s.slice(0, 50) + "..."
                          = s
                        %span.label.label-danger
                          - if furniture.price.to_s.strip != ""
                            = '$' + furniture.price.to_s
                          - else
                            Price N/A
                        %span.label.label-info
                          = Geokit::LatLng.new(furniture.latitude, furniture.longitude).distance_to(@currentLocation).round(1).to_s+" miles"
                        %span.label.label-success
                          = furniture.created_at.to_time.to_formatted_s(:db).to_s.slice(0, 10)
                        %br
                        %br
                        .row
                          .col-md-12.text-center
                            = button_to 'delete it', "/furnitures/#{furniture.id}", method: :delete, data: { confirm: "Are You Sure?" }, class: "btn btn-default text-center"