config/routes.rb
Rails.application.routes.draw do
  resources :profiles

  # resources :watchlists

  root 'application#welcome'
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  # devise_for :users
  resources :furnitures#, except: :create
  resources :profiles

  get '/my_watch_list', to: 'watchlists#show'
  get '/my_watch_list/edit', to: 'watchlists#edit'
  post '/furnitures/:id', to: 'furnitures#add_to_watch_list'
  post '/my_watch_list/:furniture_id', to: 'watchlists#unwatch'
  # get '/video/:token', to: 'furnitures#create'
  get '/team', to: 'application#team'
  get '/search', to: 'furnitures#search'
  # resources :users



  # get '/welcome', to: 'application#welcome'
end

app/models/watchlist.rb
class Watchlist < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :furnitures
end

app/controllers/watchlists_controller.rb
class WatchlistsController < ApplicationController
  before_action :set_watchlist, only: [:show, :edit, :update, :destroy, :unwatch]

  respond_to :html

  def index
    @watchlists = Watchlist.all
    respond_with(@watchlists)
  end

  def show
    address = current_user.address
    # @currentLocation = address
    tmp = Geokit::Geocoders::GoogleGeocoder.geocode(address)
    if tmp.success
      @currentLocation = [tmp.lat, tmp.lng]
    else
      @currentLocation = nil
    end
    respond_with(@watchlist)
  end

  def new
    @watchlist = Watchlist.new
    respond_with(@watchlist)
  end

  def edit
  end

  def unwatch
    @furniture = @watchlist.furnitures.find(params[:furniture_id])
    if @watchlist && @furniture
      @furniture.watchlists.delete(@watchlist)
    end
    render 'watchlists/show'
    # @furniture.watchlists.destroy(@watchlist)
  end

  def create
    @watchlist = Watchlist.new(watchlist_params)
    @watchlist.save
    respond_with(@watchlist)
  end

  def update
    @watchlist.update(watchlist_params)
    respond_with(@watchlist)
  end

  def destroy
    @watchlist.destroy
    respond_with(@watchlist)
  end


  private
    def set_watchlist
      @watchlist = current_user.watchlist
    end

    def watchlist_params
      params[:watchlist]
    end
end

app/helpers/watchlists_helper.rb
module WatchlistsHelper
end

app/views/watchlists/_form.html.haml
= form_for @watchlist do |f|
  - if @watchlist.errors.any?
    #error_explanation
      %h2= "#{pluralize(@watchlist.errors.count, "error")} prohibited this watchlist from being saved:"
      %ul
        - @watchlist.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/watchlists/edit.html.haml
%h1 Editing watchlist

= render 'form'

= link_to 'Show', @watchlist
\|
= link_to 'Back', watchlists_path

app/views/watchlists/index.html.haml
-#%table
-#  %thead
-#    %tr
-#      %th
-#      %th
-#      %th
      
  %tbody
    - @watchlists.each do |watchlist|
      %tr
        %td= link_to 'Show', watchlist
        %td= link_to 'Edit', edit_watchlist_path(watchlist)
        %td= link_to 'Destroy', watchlist, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Watchlist', new_watchlist_path

app/views/watchlists/new.html.haml
%h1 New watchlist

= render 'form'

= link_to 'Back', watchlists_path

app/views/watchlists/show.html.haml
%section.content-wrapper
  .container
    .row
      .col-md-12
        .content-box
          %h3.text-center My Watch List
          .row
            .col-md-12
              .slide-about-people
                - @watchlist.furnitures.each do |furniture|
                  .people-block
                    %figure
                      - if furniture.picture1 != nil && furniture.picture1.to_s.strip != ""
                        = image_tag furniture.picture1, size: '300x250'
                      - else
                        = image_tag 'default.jpg', size: "300x250"
                    .people-desc
                      %a{:href => "#{profile_path(furniture.user.profile)}", :float => "right"}
                        = furniture.user.name
                      %span.people-name
                        %a{:href => "/furnitures/#{furniture.id}"}
                          = furniture.title
                      %p.line-break
                        - s = furniture.description.to_s.strip
                        - if s.length > 50
                          - s = s.slice(0, 50) + "..."
                        = s
                      %span.label.label-danger
                        - if furniture.price.to_s.strip != ""
                          = '$' + furniture.price.to_s
                        - else
                          Price N/A
                      %span.label.label-info
                        = Geokit::LatLng.new(furniture.latitude, furniture.longitude).distance_to(@currentLocation).round(2).to_s+" miles"
                      %span.label.label-success
                        = furniture.created_at.to_time.to_formatted_s(:db).to_s.slice(0, 10)
                      %br
                      %br
                      .row
                        .col-md-12.text-center
                          = button_to 'unwatch', "/my_watch_list/#{furniture.id}", method: :post, data: { confirm: "Are You Sure?" }, class: "btn btn-default text-center"