config/routes.rb
Rails.application.routes.draw do
  resources :profiles

  # resources :watchlists

  root 'application#welcome'
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  # devise_for :users
  resources :furnitures#, except: :create
  resources :profiles

  get '/my_watch_list', to: 'watchlists#show'
  get '/my_watch_list/edit', to: 'watchlists#edit'
  post '/furnitures/:id', to: 'furnitures#add_to_watch_list'
  post '/my_watch_list/:furniture_id', to: 'watchlists#unwatch'
  # get '/video/:token', to: 'furnitures#create'
  get '/team', to: 'application#team'
  get '/search', to: 'furnitures#search'
  # resources :users



  # get '/welcome', to: 'application#welcome'
end

app/models/furniture.rb
require 'file_size_validator'

class Furniture < ActiveRecord::Base
  mount_uploader :picture1, PictureUploader
  mount_uploader :picture2, PictureUploader
  mount_uploader :picture3, PictureUploader
  mount_uploader :picture4, PictureUploader

  belongs_to :user
  has_and_belongs_to_many :watchlists

end

app/controllers/furnitures_controller.rb
class FurnituresController < ApplicationController

  # before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_furniture, only: [:show, :edit, :update, :destroy, :add_to_watch_list]

  # GET /furnitures
  # GET /furnitures.json
  def index
    @furnitures = []
    Furniture.all.each do |f|
      if f.user_id != current_user.id
          @furnitures.append(f)
      end
    end
    address = current_user.address
    tmp = Geokit::Geocoders::GoogleGeocoder.geocode(address)
    @currentLocation = [tmp.lat, tmp.lng]
    @miles = 5
    @furnitures.sort!{|x,y| Geokit::LatLng.new(x.latitude, x.longitude).distance_to(@currentLocation)<=>Geokit::LatLng.new(y.latitude, y.longitude).distance_to(@currentLocation)}
    @count = @furnitures.size
    @tag = "furnitures"
    @price = ">$1000"
  end

  def search
    @tag = params[:tag]
    address = current_user.address
    tmp = Geokit::Geocoders::GoogleGeocoder.geocode(address)
    @currentLocation = [tmp.lat, tmp.lng]
    @price = params[:price]
    @miles = params[:miles]
    furnitureAll = Furniture.all
    @furnitures = []
    furnitureAll.each do |f|
      location = Geokit::LatLng.new(f.latitude, f.longitude)
      if f.user_id != current_user.id and f.tag == @tag and f.price.to_i <= @price.to_i and location.distance_to(@currentLocation) <= @miles.to_i
        @furnitures.append(f)
      end
    end
    @furnitures.sort!{|x,y| Geokit::LatLng.new(x.latitude, x.longitude).distance_to(@currentLocation)<=>Geokit::LatLng.new(y.latitude, y.longitude).distance_to(@currentLocation)}
    @count = @furnitures.size
    render 'furnitures/index'
  end


  # GET /furnitures/1
  # GET /furnitures/1.json
  def show
    address = current_user.address
    # @currentLocation = address
    tmp = Geokit::Geocoders::GoogleGeocoder.geocode(address)
    if tmp.success
      @currentLocation = [tmp.lat, tmp.lng]
      userlocation = Geokit::LatLng.new(@furniture.latitude, @furniture.longitude)
      @distance = userlocation.distance_to(@currentLocation)
    else
      @currentLocation = nil
    end
    @related_furnitures = Furniture.where(tag: @furniture.tag).where.not(id: @furniture.id).order("RANDOM()").limit(4)
  end

  # GET /furnitures/new
  def new
    @furniture = Furniture.new
  end

  # GET /furnitures/1/edit
  def edit
  end

  def add_to_watch_list
    @watchlist = current_user.watchlist
    unless @watchlist.furniture_ids.include?(@furniture.id)
      @watchlist.furnitures << @furniture
    end
    @related_furnitures = Furniture.where(tag: @furniture.tag).where.not(id: @furniture.id).order("RANDOM()").limit(4)
    flash[:notice] = "You watched this furniture"
    render :show
  end

  # POST /furnitures
  # POST /furnitures.json
  def create
    @furniture = Furniture.new(furniture_params)
    @furniture.user = current_user
    @furniture.address = current_user.address
    @furniture.phone = current_user.phone
    @furniture.email = current_user.email
    @location = Geokit::Geocoders::GoogleGeocoder.geocode @furniture.address
    if @location.success
      @furniture.latitude = @location.lat
      @furniture.longitude = @location.lng
    end
    respond_to do |format|
      if @furniture.save
        format.html { redirect_to @furniture, notice: 'Furniture was successfully created.' }
        format.json { render :show, status: :created, location: @furniture }
      else
        format.html { render :new }
        format.json { render json: @furniture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /furnitures/1
  # PATCH/PUT /furnitures/1.json
  def update
    respond_to do |format|
      if @furniture.update(furniture_params)
        format.html { redirect_to @furniture, notice: 'Furniture Has Been Successfully Updated.' }
        format.json { render :show, status: :ok, location: @furniture }
      else
        format.html { render :edit }
        format.json { render json: @furniture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /furnitures/1
  # DELETE /furnitures/1.json
  def destroy
    @furniture.destroy
    respond_to do |format|
      format.html { redirect_to furnitures_url, notice: 'Furniture Has Been Successfully Deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_furniture
      @furniture = Furniture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def furniture_params
      params.require(:furniture).permit(:title, :tag, :picture1, :picture2, :picture3, :picture4, :price, :description, :email, :phone, :latitude, :longitude, :video, :oldness)
    end
end

app/helpers/furnitures_helper.rb
module FurnituresHelper
end

app/views/furnitures/_form.html.haml
= form_for @furniture do |f|
  - if @furniture.errors.any?
    #error_explanation
      %h2= "#{pluralize(@furniture.errors.count, "error")} prohibited this furniture from being saved:"
      %ul
        - @furniture.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    .row
      .col-md-12
        .col-md-3.text-right
          = f.label :title, "Furniture Name"
        .col-md-6
          = f.text_field :title, {class: "form-control", placeholder: "Furniture Name"}
  .form-group
    .row
      .col-md-12
        .col-md-3.text-right
          = f.label :tag, "Furniture Type"
        .col-md-6
          = f.select :tag, ['Chair', 'Table', 'Bed', 'Sofa', 'Lamp', 'Mattress', 'Microwave', 'Shelf'], {}, {class: "form-control"}
  .form-group
    .row
      .col-md-12
        .col-md-3.text-right
          = f.label :picture1
        .col-md-6
          = f.file_field :picture1
  .form-group
    .row
      .col-md-12
        .col-md-3.text-right
          = f.label :picture2
        .col-md-6
          = f.file_field :picture2
  .form-group
    .row
      .col-md-12
        .col-md-3.text-right
          = f.label :picture3
        .col-md-6
          = f.file_field :picture3
  .form-group
    .row
      .col-md-12
        .col-md-3.text-right
          = f.label :picture4
        .col-md-6
          = f.file_field :picture4
  .form-group
    .row
      .col-md-12
        .col-md-3.text-right
          = f.label :price
        .col-md-6
          = f.text_field :price, {class: "form-control", placeholder: "Propose a price for your furniture"}
  .form-group
    .row
      .col-md-12
        .col-md-3.text-right
          = f.label :oldness
        .col-md-6
          = f.text_field :oldness, {class: "form-control", placeholder: "How Long Did You Use The Furniture?"}
  .form-group
    .row
      .col-md-12
        .col-md-3.text-right
          = f.label :description
        .col-md-6
          = f.text_area :description, {class: "form-control", placeholder: "Give Some Detailed Descriptions About Your Furniture"}
  .form-group
    .row
      .col-md-12
        .col-md-3.text-right
          = f.label :video, "Add A Video For Your Furniture"
        .col-md-6
          %ziggeo{"ziggeo-input_bind" => "videotoken"}
          = f.text_field :video, {id: "hidden_token"}
  .row.actions
    .col-md-12.text-center
      = f.submit "POST", class: "btn btn-default"

:javascript
  $(document).ready(function(){
      $("#hidden_token").hide();
      ZiggeoApi.Events.on("submitted", function (data) {
      	document.getElementById("hidden_token").value = data.video.token;
      });
  });

app/views/furnitures/_furniture_brief.html.haml
%li
  %a{:href => "#{furniture_path(furniture)}"}
    - if furniture.picture1 != nil && furniture.picture1.to_s != ""
      = image_tag furniture.picture1, size: "45x45"
    - else
      = image_tag "default.jpg", size: "45x45"
    = furniture.title
  %a{:href => "#{profile_path(furniture.user.profile)}", :float => "right"}
    = furniture.user.name
  %p
    - s = furniture.description.to_s.strip
    - if s.length > 38
      - s = s.slice(0, 38) + "..."
    = s
  %p
    %span.label.label-danger
      - doller = furniture.price.to_s.strip
      - if doller != ""
        = "$" + furniture.price.to_s
      - else
        N/A
    %span.label.label-info
      = furniture.tag
    %span.label.label-primary
      = Geokit::LatLng.new(furniture.latitude, furniture.longitude).distance_to(currentLocation).round(1).to_s+" miles"
    -#  distance
    %span.label.label-success
      = furniture.created_at.to_time.to_formatted_s(:db).to_s.slice(0, 10)

app/views/furnitures/edit.html.haml
%hr
.outter
  %section.content-wrapper
    .container
      %section.content-wrapper
        .container
          .row
            .col-md-12
              .content-box
                %h3 Editing furniture info
                = render 'form'
= link_to 'Show', @furniture
\|
= link_to 'Back', furnitures_path

app/views/furnitures/index.html.haml
.row
  .col-md-12
    .col-md-8
      .row
        .product-order
          .row
            .col-md-12.text-center
              - if @price == ">$1000"
                = "#{@count} results for #{@tag}!"
              - else
                = "#{@count} results for #{@tag} between $0 and $#{@price}, #{@miles} miles from you!"
          %hr
          %form{:action => "search"}
            .row
              .col-md-12
                .col-md-4
                  %select.form-control{:name => "price"}
                    %option{:value => "5"}$0 - $5
                    %option{:value => "10"}$0 - $10
                    %option{:value => "25"}$0 - $25
                    %option{:value => "50"}$0 - $50
                    %option{:value => "100"}$0 - $100
                    %option{:value => "200"}$0 - $200
                    %option{:value => "500"}$0 - $500
                    %option{:value => "1000"}$0 - $1000
                .col-md-3
                  %select.form-control{:name => "miles"}
                    %option{:value => 1}Within 1 mile
                    %option{:value => 5}Within 5 miles
                    %option{:value => 10}Within 10 miles
                    %option{:value => 30}Within 30 miles
                    %option{:value => 10000}Within than 10000 miles
                .col-md-3
                  %select.form-control{:name => "tag"}
                    %option{:value => "Chair"} Chair
                    %option{:value => "Table"} Table
                    %option{:value => "Bed"} Bed
                    %option{:value => "Sofa"} Sofa
                    %option{:value => "Lamp"} Lamp
                    %option{:value => "Mattress"} Mattress
                    %option{:value => "Microwave"} Microwave
                    %option{:value => "Shelf"} Shelf
                .col-md-2
                  %input.btn.btn-default.form-control{:type => "submit", :value => "Search"}
      %hr
      #map-canvas}
    .col-md-4.scroll-view
      %section.content-wrapper
        .widget-box.sidebar
          %h3.wdgt-title PRODUCT LIST
          %ul.wdgt-product
            -@furnitures.each do |furniture|
              = render 'furniture_brief', furniture: furniture, currentLocation: @currentLocation
%br


-#= content_tag :div, class: "furnitures_class", data: {current: @currentLocation} do end
= content_tag :div, class: "furnitures_class", data: {furnitures: @furnitures, current: @currentLocation, miles: @miles} do end


:javascript
  $(document).ready(function() {
    var currentLocation = $('.furnitures_class').data('current');
    var miles = $('.furnitures_class').data('miles');
    var mapOptions = {
      zoom: RadiusToZoom(miles),
      center: new google.maps.LatLng(currentLocation[0], currentLocation[1])
    };
    var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
    var furnitures = $('.furnitures_class').data('furnitures');
    function initialize() {
        var here = new google.maps.Marker({
            position: new google.maps.LatLng(currentLocation[0], currentLocation[1]),
            map: map,
            icon: 'http://library.csun.edu/images/google_maps/marker-blue.png'
        })

        var i;
        for (i = 0; i < furnitures.length; i++) {
            var latlng = new google.maps.LatLng(furnitures[i].latitude, furnitures[i].longitude);
            var title = furnitures[i].title;

            var marker = new google.maps.Marker({
                position: new google.maps.LatLng(furnitures[i].latitude, furnitures[i].longitude),
                map: map,
                title: title
            });
            google.maps.event.addListener(marker, 'click', (function(marker, i) {
                return function(){
                    var distance = 3;
                    var pic;
                    if(furnitures[i].picture1 == null || furnitures[i].picture1.toString() == "") {
                    	pic = "/images/aeroplane.png";
                    } else {
                    	pic = "/uploads/furniture/"+furnitures[i].id+"/picture1.jpg";
                    }
                    var description = "<div><div class='row'><div class='col-md-12'><div class='col-md-12'><a href='/furnitures/" + furnitures[i].id + "'><h3>"+
                                       furnitures[i].title + "</h3></a></div></div></div>" +
                                       "<div class='row'><div class='col-md-12'><div class='col-md-6'><p><span class='label label-danger'>\$" + furnitures[i].price +
                                       "</span><span class='label label-info'>" +furnitures[i].tag +
                                       "</span><span class='label label-success'>" + furnitures[i].created_at.substr(0, 10)
                                       + "</span></p><p>" + furnitures[i].description +
                                       "</p></div><div class='col-md-3'><img alt='Picture1' height='100' src='" + pic + "' width='100' />" + "</div></div></div></div>";
                    new google.maps.InfoWindow({
                        content: description
                    }).open(map, marker);
                }
            })(marker, i));
        }
    }
    function RadiusToZoom(radius){
        if(radius < 1) return 12;
        return Math.round(14-Math.log(radius)/Math.LN2);
    }

    initialize();
    google.maps.event.addDomListener(window, 'load', initialize);
    //google.maps.event.trigger(map, "resize");
  });

app/views/furnitures/new.html.haml
%section.content-wrapper
  .container
    .row
      .col-md-12
        .content-box
          %h3.text-center NEW POST
          = render 'form'
-#= link_to 'Show', @furniture
-#= link_to 'Back', furnitures_path

app/views/furnitures/show.html.haml
%section.content-wrapper
  .container
    .row
      .col-md-4
        %br
        .content-box
          .sp-wrap
            - if @furniture.picture1 != nil && @furniture.picture1.to_s.strip != ""
              %a{:href => @furniture.picture1}
                %img{:src => @furniture.picture1}
            - else
              %a{:href => image_url("product-1.jpg")}
                %img{:src => image_url("product-1-h.jpg")}
            - if @furniture.picture2 != nil && @furniture.picture2.to_s.strip != ""
              %a{:href => @furniture.picture2}
                %img{:src => @furniture.picture2}
            - if @furniture.picture3 != nil && @furniture.picture3.to_s.strip != ""
              %a{:href => @furniture.picture3}
                %img{:src => @furniture.picture3}
            - if @furniture.picture4 != nil && @furniture.picture4.to_s.strip != ""
              %a{:href => @furniture.picture4}
                %img{:src => @furniture.picture4}
      .col-md-8
        .content-box
          .product-meta
            %h1.product-title
              = @furniture.title
            %ul.product-breadcrumb
              %li
                %a{:href => "/profiles/#{@furniture.user.profile.id}"}
                  = @furniture.user.name
              %li.current
                %a= @furniture.title
          .product-desc
            .product-price
              .price-new
                Price
                %span
                  = "$" + @furniture.price.to_s
                %a.info.cart{:href => ""}
                  %span.icon>
                    %i.icon-basket
                  = link_to 'Add to Watch List', "/furnitures/#{@furniture.id}", method: :post
            %ul.nav.nav-tabs
              %li
                %a{"data-toggle" => "tab", :href => "#video"} Video
              %li.active
                %a{"data-toggle" => "tab", :href => "#desc"} Description
              %li
                %a{"data-toggle" => "tab", :href => "#addr"} View On Map
            .tab-content{:style => "height: 500px"}
              #video.tab-pane.fade
                - if @furniture.video != ""
                  %ziggeo{"ziggeo-video" => @furniture.video}
                - else
                  No video available
              #desc.tab-pane.fade.in.active
                .row
                  .col-md-3
                    %h4 Name:
                  .col-md-8.line-break
                    %h4
                      %small= @furniture.title
                .row
                  .col-md-3
                    %h4 Category:
                  .col-md-8.line-break
                    %h4
                      %span.label.label-info= @furniture.tag
                .row
                  .col-md-3
                    %h4 Description:
                  .col-md-8.line-break
                    %h4
                      %small= @furniture.description
                .row
                  .col-md-3
                    %h4 Oldness:
                  .col-md-8.line-break
                    %h4
                      %small= @furniture.oldness
                .row
                  .col-md-3
                    %h4 Contact's Email:
                  .col-md-8.line-break
                    %h4
                      %small= @furniture.email
                .row
                  .col-md-3
                    %h4 Phone Number:
                  .col-md-8.line-break
                    %h4
                      %small= @furniture.phone
              #addr.tab-pane.fade
                %b Address:
                - if @furniture.user != nil
                  = @furniture.address
                %br
                %b
                  %p{:style => 'color:red'}
                #map-location
%section.content-wrapper
  .container
    .row
      .col-md-12
        .box-title
          %h2 YOU MAY ALSO LIKE ...
  .row
    .col-md-12
      -@related_furnitures.each do |furniture|
        .col-md-3.col-xs-6
          .product-block
            .product-image
              %a{:href => "javascript:;"}
                %figure
                  - if furniture.picture1 != nil && furniture.picture1.to_s.strip != ""
                    = image_tag furniture.picture1, size: '300x250'
                  - else
                    = image_tag 'default.jpg', size: "300x250"
            .product-meta
              .product-action
                = link_to '<i class="icon-basket"></i>Add to WatchList'.html_safe, "/furnitures/#{furniture.id}", method: :post, class: "addcart"
                %a.wishlist
                  %i.fa.fa-heart
                %a.compare.span{:href => "#{profile_path(furniture.user.profile)}"}
                  %i.fa.fa-eye
                  = furniture.user.name
            .product-info
              %a{:href => "/furnitures/#{furniture.id}"}
                %h5.product-name= furniture.title
              .product-price
                %span.newprice== $ #{furniture.price}
            .product-rating
              %i.fa.fa-star
              %i.fa.fa-star
              %i.fa.fa-star
              %i.fa.fa-star
              %i.fa.fa-star

= content_tag :div, class: "furniture_class", data: {furniture: @furniture, current: @currentLocation, distance: @distance} do end

:javascript
  $(document).ready(function() {

    var directionsDisplay;
    var directionsService = new google.maps.DirectionsService();
    var location = $('.furniture_class').data('furniture');
    var currentLocation = $('.furniture_class').data('current');
    var twoplace = $('.furniture_class').data('distance')
    var mapOptions = {
      zoom: RadiusToZoom(twoplace),
      center: new google.maps.LatLng(location.latitude, location.longitude)
    };
    var map;
    function initialize() {
      //var here = new google.maps.Marker({
      //  position: new google.maps.LatLng(location.latitude, location.longitude),
      //  map: map
      //});
      if(currentLocation != null){
        //var current = new google.maps.Marker({
        //  position: new google.maps.LatLng(currentLocation[0], currentLocation[1]),
        //  map: map,
        //  icon: 'http://library.csun.edu/images/google_maps/marker-blue.png'
        //})
        directionsDisplay = new google.maps.DirectionsRenderer();

        directionsDisplay.setMap(map);

        var request = {
            origin: new google.maps.LatLng(location.latitude, location.longitude),
            destination: new google.maps.LatLng(currentLocation[0], currentLocation[1]),
            travelMode: google.maps.TravelMode.WALKING
        };
        directionsService.route(request, function(response, status) {
          if (status == google.maps.DirectionsStatus.OK) {
            directionsDisplay.setDirections(response);
          }
        });
      }
    }

    function RadiusToZoom(radius){
      if(radius < 1) return 12;
      return Math.round(14-Math.log(radius)/Math.LN2);
    }

    $("#addr").show(function() {
      map = new google.maps.Map(document.getElementById('map-location'), mapOptions);
      initialize();

      //google.maps.event.trigger(map, 'resize');
    });
    google.maps.event.addDomListener(window, 'load', initialize);


  });