config/routes.rb
Rails.application.routes.draw do
  resources :profiles

  # resources :watchlists

  root 'application#welcome'
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  # devise_for :users
  resources :furnitures#, except: :create
  resources :profiles

  get '/my_watch_list', to: 'watchlists#show'
  get '/my_watch_list/edit', to: 'watchlists#edit'
  post '/furnitures/:id', to: 'furnitures#add_to_watch_list'
  post '/my_watch_list/:furniture_id', to: 'watchlists#unwatch'
  # get '/video/:token', to: 'furnitures#create'
  get '/team', to: 'application#team'
  get '/search', to: 'furnitures#search'
  # resources :users



  # get '/welcome', to: 'application#welcome'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title FUrniTURE
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag "https://maps.googleapis.com/maps/api/js?v=3.exp"
    = csrf_meta_tags
    %link{:href => "//assets.ziggeo.com/css/ziggeo-betajs-player.min.css", :rel => "stylesheet"}/
    %script{:src => "//assets.ziggeo.com/js/ziggeo-jquery-json2-betajs-player.min.js"}
    :javascript
      ZiggeoApi.token = "d71ecbd682e677ecd959316ac837e2cc";
  %body
    .outter
      %section.top-block
        .container
          .row
            .col-md-12
              .sel-top
      %section.header
        .container
          .row
            .col-sm-5
              .sitelogo-block
                .logo
                  %a{:href => "/"}
                    = image_tag 'logonew(1).png', size: "85x85"
                .titledesc
                  %a{:href => "/"}
                    %h1 FU<small>rni</small>TURE
                    %span Best Used Furniture Trading Platform
            .col-sm-7
              .topinfo-block
                - if user_signed_in?
                  %a.info{:href => ""}
                    %span.icon>
                      %i.icon-location
                    = link_to 'Map', furnitures_path
                  %a.info{:href => ""}
                    %span.icon>
                      %i.icon-money
                    = link_to 'Sell Furniture', new_furniture_path
                  %a.info{:href => ""}
                    %span.icon>
                      %i.icon-menu
                    = link_to 'View Your Post', profile_path(current_user.profile)
                  %a.info.cart{:href => ""}
                    %span.icon>
                      %i.icon-basket
                    = link_to 'Watch List', '/my_watch_list'
                  %a.info.login{:href => ""}
                    %span.icon>
                      %i.icon-doc
                    = link_to 'Edit Profile', edit_user_registration_path, :class => 'navbar-link'
                  %a.info.login{:href => ""}
                    %span.icon>
                      %i.icon-lock
                    = link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'
                - else
                  %a.info.login{:href => ""}
                    %span.icon>
                      %i.icon-lock
                    = link_to "Login", new_user_session_path, :class => 'navbar-link'
                  %a.info.login{:href => ""}
                    %span.icon>
                      %i.icon-lock
                    = link_to "Sign up", new_user_registration_path, :class => 'navbar-link'
      - if notice
        %p.alert.alert-success= notice
      - if alert
        %p.alert.alert-danger= alert
      %section.navigation
        .container
          .row
            .col-md-12
              %nav.navbar.navbar-default{:role => "navigation"}
                .container-fluid
                  .navbar-header
                    %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
                      %span.sr-only Toggle navigation
                      %span.icon-bar
                      %span.icon-bar
                      %span.icon-bar
                  #bs-example-navbar-collapse-1.collapse.navbar-collapse
                    %ul.nav.navbar-nav
                      %li.dropdown
                        %a.dropdown-toggle{"data-toggle" => "dropdown"}
                          HOME
                          %b.caret
                      %li
                        %a{:href => "/team"} ABOUT US
                      %li.dropdown
                        %a.dropdown-toggle{"data-toggle" => "dropdown"}
                          PAGES
                          %b.caret
                      %li.dropdown
                        %a.dropdown-toggle{"data-toggle" => "dropdown"}
                          SHOP
                          %b.caret
                      %li.dropdown
                        %a.dropdown-toggle{"data-toggle" => "dropdown"}
                          Blog
                          %b.caret
                      %li
                        %a SHORTCODE
                      %li
                        %a CONTACT
      = yield
      %br
      .brand
        .container
          .row
            .col-md-12
              .box-title
                %h2 SPONSORS
          .row
            .col-md-12
              %ul.brands
                %li
                  = image_tag 'v42397.png', size: "100x100"
                  -#%img{:src => image_url("penn-logo.png")}
                %li
                  = image_tag 'original.png', size: "180x100"
                  -#%img{:src => image_url("original.png")}
                %li
                  = image_tag 'ziggeo.png', size: "200x120"
                  -#%img{:src => image_url("ziggeo.png")}
                %li
                  = image_tag 'Comcast_S_COLOR_BLK.png', size: "250x70"
      .container
        .row
          .col-md-12
            .shop-info
              %p FUrniTURE, best used furniture trading platform
              %a{:href => "/team"}
                ABOUT US
              %p
                Powered by
                %a Bootstrap
                -#%ziggeo
                -#%ziggeo{"ziggeo-video" => "5f582e5151bf0520f7c3dee935836d5d"}
                -#%ziggeo{"ziggeo-input_bind" => "videotoken"}
                -#:javascript
                -#  ZiggeoApi.Events.on("submitted", function (data) {
                -#  	alert("Submitted a new video with token '" + data.video.token + "'!");
                -#  });